In [219]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib 
matplotlib.rcParams["figure.figsize"] = (20,10)

In [ ]:
#Pre-Process the Dataset

In [220]:
data1 = pd.read_csv("house_prices.csv")
data1.head()

,Title,Sub_title,Price,Address,Baths,Land size,Beds,House size,Location,Description,Post_URL,Seller_name,Seller_type,published_date,Geo_Address,Lat,Lon
0,House with Land for Sale in Matara for sale,"Posted on 06 Nov 2:32 pm, Matara City, Matara","Rs 5,400,000","Gangodagama Roard,Hakmana,Matara.",1,50.0 perches,3,"1,600.0 sqft","Matara City, Matara","Land for sale with house Matara,Hakmana Gangod...",https://ikman.lk/en/ad/house-with-land-for-sal...,Ishara Dilshan,Member,2021-11-06 14:32:00,"Matara City, Matara, Sri Lanka",80.500000,6.166670
1,à¶ à¶½à·à¶­à· à¶à·à¶¸à¶» 3 à¶ à¶à·à· à...,"Posted on 24 Oct 7:27 am, Athurugiriya, Colombo","Rs 16,800,000",Athurugiriya Galwarusapare,3,8.0 perches,3,"1,480.0 sqft","Athurugiriya, Colombo",*House For Sale In Athurugiriya *Galwarusapare...,https://ikman.lk/en/ad/alut-kaamr-3-k-grh-bhaa...,DILRUWAN REAL ESTATE,Premium-Member,2021-10-24 07:27:00,"Athurugiriya, Colombo, Sri Lanka",79.989929,6.877246
2,Kelaniya - House on 20P Land for sale for sale,"Posted on 17 Nov 5:19 pm, Kelaniya, Gampaha","Rs 20,000,000",Kelaniya- Ranaviru Maldeniya Road,2,20.0 perches,3,"2,800.0 sqft","Kelaniya, Gampaha","Kelaniya- Biyagama road, Ranaviru Maladeniya R...",https://ikman.lk/en/ad/kelaniya-house-on-20p-l...,Provident Paradise (Pvt) Ltd,Member,2021-11-17 17:19:00,"Kelaniya, Gampaha, Sri Lanka",79.914926,6.951178
3,House For Sale in Pamankada Lane Wellawatte Co...,"Posted on 17 Nov 5:07 pm, Colombo 6, Colombo","Rs 187,000,000",Pamankada Lane Wellawatte Colombo.06,5,22.0 perches,5,"4,000.0 sqft","Colombo 6, Colombo",22 Perches House For Sale in Pamankada Lane We...,https://ikman.lk/en/ad/house-for-sale-in-paman...,Colombo Construction Property Developers,Premium-Member,2021-11-17 17:07:00,"Colombo 6, Colombo, Sri Lanka",80.016670,6.866670
4,House For Sale - Attidiya for sale,"Posted on 17 Nov 5:06 pm, Dehiwala, Colombo","Rs 1,300,000",MainRoad Attidiya,1,6.3 perches,2,900.0 sqft,"Dehiwala, Colombo",*à¶ à¶­à·à¶­à·à¶©à·à¶º à¶´à·âà¶»à¶¯à·à·...,https://ikman.lk/en/ad/house-for-sale-attidiya...,Lakdinu Houses,Member,2021-11-17 17:06:00,"Dehiwala, Colombo, Sri Lanka",79.880242,6.838232

In [221]:
data1.shape

(15327, 17)

In [222]:
data1['Brand New'] = data1['Title'].str.contains('Brand New').astype(int)
data1['Brand New'] = data1['Title'].apply(lambda x:1 if 'Brand New' in x else 0)
data1.head(50)

,Title,Sub_title,Price,Address,Baths,Land size,Beds,House size,Location,Description,Post_URL,Seller_name,Seller_type,published_date,Geo_Address,Lat,Lon,Brand New
0,House with Land for Sale in Matara for sale,"Posted on 06 Nov 2:32 pm, Matara City, Matara","Rs 5,400,000","Gangodagama Roard,Hakmana,Matara.",1,50.0 perches,3,"1,600.0 sqft","Matara City, Matara","Land for sale with house Matara,Hakmana Gangod...",https://ikman.lk/en/ad/house-with-land-for-sal...,Ishara Dilshan,Member,2021-11-06 14:32:00,"Matara City, Matara, Sri Lanka",80.500000,6.166670,0
1,à¶ à¶½à·à¶­à· à¶à·à¶¸à¶» 3 à¶ à¶à·à· à...,"Posted on 24 Oct 7:27 am, Athurugiriya, Colombo","Rs 16,800,000",Athurugiriya Galwarusapare,3,8.0 perches,3,"1,480.0 sqft","Athurugiriya, Colombo",*House For Sale In Athurugiriya *Galwarusapare...,https://ikman.lk/en/ad/alut-kaamr-3-k-grh-bhaa...,DILRUWAN REAL ESTATE,Premium-Member,2021-10-24 07:27:00,"Athurugiriya, Colombo, Sri Lanka",79.989929,6.877246,0
2,Kelaniya - House on 20P Land for sale for sale,"Posted on 17 Nov 5:19 pm, Kelaniya, Gampaha","Rs 20,000,000",Kelaniya- Ranaviru Maldeniya Road,2,20.0 perches,3,"2,800.0 sqft","Kelaniya, Gampaha","Kelaniya- Biyagama road, Ranaviru Maladeniya R...",https://ikman.lk/en/ad/kelaniya-house-on-20p-l...,Provident Paradise (Pvt) Ltd,Member,2021-11-17 17:19:00,"Kelaniya, Gampaha, Sri Lanka",79.914926,6.951178,0
3,House For Sale in Pamankada Lane Wellawatte Co...,"Posted on 17 Nov 5:07 pm, Colombo 6, Colombo","Rs 187,000,000",Pamankada Lane Wellawatte Colombo.06,5,22.0 perches,5,"4,000.0 sqft","Colombo 6, Colombo",22 Perches House For Sale in Pamankada Lane We...,https://ikman.lk/en/ad/house-for-sale-in-paman...,Colombo Construction Property Developers,Premium-Member,2021-11-17 17:07:00,"Colombo 6, Colombo, Sri Lanka",80.016670,6.866670,0
4,House For Sale - Attidiya for sale,"Posted on 17 Nov 5:06 pm, Dehiwala, Colombo","Rs 1,300,000",MainRoad Attidiya,1,6.3 perches,2,900.0 sqft,"Dehiwala, Colombo",*à¶ à¶­à·à¶­à·à¶©à·à¶º à¶´à·âà¶»à¶¯à·à·...,https://ikman.lk/en/ad/house-for-sale-attidiya...,Lakdinu Houses,Member,2021-11-17 17:06:00,"Dehiwala, Colombo, Sri Lanka",79.880242,6.838232,0
5,House For Sale in Batharamulle for sale,"Posted on 17 Nov 5:04 pm, Talawatugoda, Colombo","Rs 55,000,000",NaN,4,11.0 perches,4,"3,300.0 sqft","Talawatugoda, Colombo",House For Sale in Batharamulle HIGHLY RESIDEN...,https://ikman.lk/en/ad/house-for-sale-in-batha...,Lassana Gedara Real Estate,Premium-Member,2021-11-17 17:04:00,"Talawatugoda, Colombo, Sri Lanka",80.016670,6.866670,0
6,Brand New Luxury House For Sale Kandy Peradeni...,"Posted on 21 Oct 12:47 pm, Kandy City, Kandy","Rs 45,000,000",NaN,4,10.0 perches,4,"4,100.0 sqft","Kandy City, Kandy",Brand New Luxury House For Sale Kandy Peradeni...,https://ikman.lk/en/ad/brand-new-luxury-house-...,Tele Ads,Member,2021-10-21 12:47:00,"Kandy City, Kandy, Sri Lanka",80.625828,7.295044,1
7,House for Sale in Kesbewa for sale,"Posted on 17 Nov 4:56 pm, Piliyandala, Colombo","Rs 16,700,000","Kudamaduwa Rd,Honnanthra",3,9.0 perches,3,"1,400.0 sqft","Piliyandala, Colombo",ð´ House for Sale in Kesbewa================...,https://ikman.lk/en/ad/house-for-sale-in-kesbe...,Sell fast | Kesbawa Isuru Communication,Member,2021-11-17 16:56:00,"Piliyandala, Colombo, Sri Lanka",79.922703,6.801844,0
8,Brand New House For Sale InThalwathugoda for sale,"Posted on 17 Nov 4:56 pm, Talawatugoda, Colombo","Rs 50,000,000","Hokandara Road , Thalawathugoda",4,10.0 perches,4,"4,000.0 sqft","Talawatugoda, Colombo",House for sale in Thalawathugoda off Thalawath...,https://ikman.lk/en/ad/brand-new-house-for-sal...,JPR Properties,Premium-Member,2021-11-17 16:56:00,"Talawatugoda, Colombo, Sri Lanka",80.016670,6.866670,1
9,à¶±à·à·à· à¶à¶©à¶¸à¶à· à·à·à¶à·à¶«à·...,"Posted on 17 Nov 4:47 pm, Kadawatha, Gampaha","Rs 16,000,000",163/126à¶¶à¶à¶à¶½à·à·à¶­à·à¶­ à¶à·à¶»à·...,1,"3,000.0 perches",3,"2,000.0 sqft","Kadawatha, Gampaha",à¶´à¶»à·à¶ à·à· à·à·à·à·à·à·,https://ikman.lk/en/ad/iddmk-nivs-for-sale-gam...,Manoj Pradeep,Premium-Member,2021-11-17 16:47:00,"Kadawatha, Gampaha, Sri Lanka",79.951267,7.001966,0
10,Newly Build House for Sale - Siyabalape for sale,"Posted on 17 Nov 4:45 pm, Gampaha City, Gampaha","Rs 19,500,000",Siyabalape South,2,10.0 perches,4,"5,000.0 sqft","Gampaha City, Gampaha",Newly Build House for Sale - SiyabalapeUrgentl...,https://ikman.lk/en/ad/newly-build-house-for-s...,Kasun Wijesena,Premium-Member,2021-11-17 16:45:00,"Gampaha City, Gampaha, Sri Lanka",80.000000,7.133330,0
11,"9.85 Perches House for Sale in Ambatenna, Katu...","Posted on 17 Nov 4:43 pm, Katugastota, Kandy","Rs 11,500,000",Ambathenna -Katugastota,1,9.85 perches,3,"1,800.0 sqft","Katugastota, Kandy",â¢ 9.85 Perch Land with 1800 SQFT a House W...,https://ikman.lk/en/ad/985-perches-house-for-s...,First Team Real Estate,Premium-Member,2021-11-17 16:43:00,"Katugastota, Kandy, Sri Lanka",80.624955,7.322084,0
12,House for Sale - Negambo for sale,"Posted on 17 Nov 4:31 pm, Negombo, Gampaha","Rs 26,500,000","Dalupatha, Negambo",3,10.5 perches,4,"3,100.0 sqft","Negombo, Gampaha",# Brand New Luxury Complete Box Morden 2 St...,https://ikman.lk/en/ad/house-for-sale-negambo-...,MSM Homes,Premium-Member,2021-11-17 16:31:00,"Negombo, Gampaha, Sri Lanka",79.843249,7.206416,0
13,à¶­à¶±à· à¶¸à·à¶½à· à¶ à¶½à·à¶­à· à¶±à·à...,"Posted on 17 Nov 4:30 pm, Malabe, Colombo","Rs 19,000,000","Malabe Rd, Thunhadahena",2,11.4 perches,4,"1,900.0 sqft","Malabe, Colombo",Modern Brand New Storied House for Sale in Mal...,https://ikman.lk/en/ad/tni-mhl-alut-nivsk-for-...,Siyaka Land Sale,Premium-Member,2021-11-17 16:30:00,"Malabe, Colombo, Sri Lanka",79.954619,6.904072,0
14,House for Sale in Navali for sale,"Posted on 17 Nov 4:30 pm, Jaffna City, Jaffna","Rs 11,000,000",Navali,1,80.0 perches,3,"1,100.0 sqft","Jaffna City, Jaffna",House For Sale In Navalið¡ ð¯Land size- 80...,https://ikman.lk/en/ad/house-for-sale-in-naval...,RE/MAX NORTH,Member,2021-11-17 16:30:00,"Jaffna City, Jaffna, Sri Lanka",80.009172,9.664926,0
15,House for Sale in Malabe for sale,"Posted on 17 Nov 4:27 pm, Malabe, Colombo","Rs 16,500,000","Thunadahena Road, Malabe",2,7.5 perches,3,"1,250.0 sqft","Malabe, Colombo",Completed Brand New Storied House for Sale in ...,https://ikman.lk/en/ad/house-for-sale-in-malab...,Siyaka Land Sale,Premium-Member,2021-11-17 16:27:00,"Malabe, Colombo, Sri Lanka",79.954619,6.904072,0
16,House for Sale in Rajagiriya for sale,"Posted on 17 Nov 4:26 pm, Rajagiriya, Colombo","Rs 6,500,000","Rajagiriya President Road, 2nd Lane",1,3.0 perches,2,950.0 sqft,"Rajagiriya, Colombo",à¶»à·à¶¢à¶à·à¶»à·à¶ºà· à¶±à·à·à· à·à·...,https://ikman.lk/en/ad/house-for-sale-in-rajag...,Field Operations,Premium-Member,2021-11-17 16:26:00,"Rajagiriya, Colombo, Sri Lanka",79.896218,6.909504,0
17,Mtlavinia hotel for sale in mt lavinia for sale,"Posted on 17 Nov 4:24 pm, Mount Lavinia, Colombo","Rs 95,000,000",Mtlavinia,10+,11.2 perches,10+,"6,000.0 sqft","Mount Lavinia, Colombo",Mtlavinia Hotel for sale 13 bedroom s 14 bathr...,https://ikman.lk/en/ad/mtlavinia-hotel-for-sal...,House Solution & Construction Rajkumar,Premium-Member,2021-11-17 16:24:00,"Mount Lavinia, Colombo, Sri Lanka",79.866418,6.842919,0
18,House for Sale - Battaramulla for sale,"Posted on 17 Nov 4:23 pm, Battaramulla, Colombo","Rs 55,000,000",NaN,5,11.0 perches,4,"3,000.0 sqft","Battaramulla, Colombo",Agent's Reference - 30645UnfurnishedPool,https://ikman.lk/en/ad/house-for-sale-battaram...,PropertyOne,Premium-Member,2021-11-17 16:23:00,"Battaramulla, Colombo, Sri Lanka",79.913892,6.897711,0
19,House with a 20p land for sale in Battaramulla...,"Posted on 17 Nov 4:23 pm, Battaramulla, Colombo","Rs 50,000,000",Battaramulla,3,20.5 perches,4,"2,900.0 sqft","Battaramulla, Colombo",House with a 20p land for sale in Battaramull...,https://ikman.lk/en/ad/house-with-a-20p-land-f...,Khane Properties (Pvt) Ltd,Premium-Member,2021-11-17 16:23:00,"Battaramulla, Colombo, Sri Lanka",79.913892,6.897711,0
20,House for Sale â Moratuwa for sale,"Posted on 17 Nov 4:22 pm, Moratuwa, Colombo","Rs 13,500,000","Egodauyana, Moratuwa",2,15.0 perches,3,"1,400.0 sqft","Moratuwa, Colombo",Moratuwa Egodauyana perches 153 Rooms 2 Bathro...,https://ikman.lk/en/ad/house-for-sale-moratuwa...,FindAPlace.lk Property Agents,Member,2021-11-17 16:22:00,"Moratuwa, Colombo, Sri Lanka",79.888881,6.790527,0
21,"House for Sale in Lunawa, Moratuwa for sale","Posted on 17 Nov 4:22 pm, Moratuwa, Colombo","Rs 24,500,000","Lunawa, Moratuwa",2,7.42 perches,4,"2,900.0 sqft","Moratuwa, Colombo",2 STORY HOUSE FOR SALE HIGHLY RESIDENTIAL AREA...,https://ikman.lk/en/ad/house-for-sale-in-lunaw...,FindAPlace.lk Property Agents,Member,2021-11-17 16:22:00,"Moratuwa, Colombo, Sri Lanka",79.888881,6.790527,0
22,"House for Sale in Kahathuduwa, Piliyandala for...","Posted on 17 Nov 4:22 pm, Piliyandala, Colombo","Rs 32,500,000","Kahathuduwa,",2,21.5 perches,4,"2,880.0 sqft","Piliyandala, Colombo","Kahathuduwa, Piliyandala21.5 perches 2 story h...",https://ikman.lk/en/ad/house-for-sale-in-kahat...,FindAPlace.lk Property Agents,Member,2021-11-17 16:22:00,"Piliyandala, Colombo, Sri Lanka",79.922703,6.801844,0
23,Nugegoda 9BR house 300m to high-level for sale,"Posted on 17 Nov 4:21 pm, Nugegoda, Colombo","Rs 27,000,000",Nugegoda 300m,5,11.2 perches,9,"3,085.0 sqft","Nugegoda, Colombo",Nugegoda house 300m to bus route high-level rd...,https://ikman.lk/en/ad/nugegoda-9br-house-300m...,House Solution & Construction Rajkumar,Premium-Member,2021-11-17 16:21:00,"Nugegoda, Colombo, Sri Lanka",79.893438,6.877014,0
24,Luxury House for Sale in Aththidiya (main Road...,"Posted on 08 Nov 4:07 pm, Dehiwala, Colombo","Rs 32,500,000",NaN,4,7.5 perches,5,"2,042.0 sqft","Dehiwala, Colombo",<<<<<<<<<<<<<<<Ground floor>>>>>>>> >>>>>>> #...,https://ikman.lk/en/ad/luxury-house-for-sale-i...,Nashath,Premium-Member,2021-11-08 16:07:00,"Dehiwala, Colombo, Sri Lanka",79.880242,6.838232,0
25,Brand New Luxury House for Sale - Kottawa for ...,"Posted on 17 Nov 4:32 pm, Kottawa, Colombo","Rs 33,000,000",Haritha uyana kottawa,3,8.0 perches,4,"3,200.0 sqft","Kottawa, Colombo",Brand new luxury house in kottawa Not a ordina...,https://ikman.lk/en/ad/brand-new-luxury-house-...,Mihiran perera,Member,2021-11-17 16:32:00,"Kottawa, Colombo, Sri Lanka",79.965234,6.841388,1
26,Brand New Well Built House for Sale in Homagam...,"Posted on 13 Nov 4:04 pm, Homagama, Colombo","Rs 28,500,000",à¶à¶§à·à·à·à¶± - à·à·à¶¸à·à¶à¶¸,3,10.2 perches,5,"2,800.0 sqft","Homagama, Colombo",ðð«ðð§ð ððð° ðð¨ð®...,https://ikman.lk/en/ad/brand-new-well-built-ho...,Asiri Properties Private Limited,Premium-Member,2021-11-13 16:04:00,"Homagama, Colombo, Sri Lanka",80.005842,6.848488,1
27,House for Sale udugampala for sale,"Posted on 15 Nov 12:22 pm, Minuwangoda, Gampaha","Rs 17,000,000","vidiyawaththa, udugampala",3,10.3 perches,5,"2,600.0 sqft","Minuwangoda, Gampaha",Three story house for sale for more informatio...,https://ikman.lk/en/ad/demahal-niwasak-vikinim...,manori,Premium-Member,2021-11-15 12:22:00,"Minuwangoda, Gampaha, Sri Lanka",80.000000,7.133330,0
28,Luxury House for Sale - Negombo for sale,"Posted on 12 Nov 3:33 pm, Negombo, Gampaha","Rs 31,000,000",325/19 dalupotha Negombo,4,12.5 perches,4,"2,882.0 sqft","Negombo, Gampaha",Advertisement for house:Brand new four-bedroom...,https://ikman.lk/en/ad/luxury-house-for-sale-n...,S Prabu (Lanka Horizons),Member,2021-11-12 15:33:00,"Negombo, Gampaha, Sri Lanka",79.843249,7.206416,0
29,House for Sale Thanabaddegama for sale,"Posted on 12 Nov 2:25 pm, Elpitiya, Galle","Rs 4,500,000","à¶­à¶±à¶¶à¶¯à·à¶¯à·à¶à¶¸,à¶à¶­à·à¶à¶³à·...",1,150.0 perches,3,750.0 sqft,"Elpitiya, Galle",à¶à·à¶»à·à¶³à· à·à¶à·à· à·à·à·à¶­ à...,https://ikman.lk/en/ad/house-for-sale-thanabad...,Sell fast | Sense Creation & Cellular,Member,2021-11-12 14:25:00,"Elpitiya, Galle, Sri Lanka",80.161905,6.291885,0
30,House for sale in Malabe for sale,"Posted on 12 Nov 11:36 am, Malabe, Colombo","Rs 14,800,000","Nippon Estate,Vihara Mawatha , Malabe",1,6.8 perches,3,"1,800.0 sqft","Malabe, Colombo","â­New Luxury Houseâ­1km to Cinec ,Saitm , SL...",https://ikman.lk/en/ad/house-for-sale-in-malab...,priyantha herath,Premium-Member,2021-11-12 11:36:00,"Malabe, Colombo, Sri Lanka",79.954619,6.904072,0
31,A Brand New Two story luxury house in nearby k...,"Posted on 25 Oct 9:07 pm, Kottawa, Colombo","Rs 27,000,000",kottawa,4,7.0 perches,4,"2,700.0 sqft","Kottawa, Colombo",à¶à·à¶§à·à¶§à·à· à¶´à¶±à·à¶±à·à¶´à·à¶§...,https://ikman.lk/en/ad/a-brand-new-two-story-l...,DSF PROPERTIES,Member,2021-10-25 21:07:00,"Kottawa, Colombo, Sri Lanka",79.965234,6.841388,1
32,House for Sale in Gampola for sale,"Posted on 14 Nov 5:25 pm, Gampola, Kandy","Rs 34,000,000","Keselwatta Road, Gampola",7,39.13 perches,10+,"4,000.0 sqft","Gampola, Kandy",LKR 34 MillionNegotiableAddress:Keselwatta Roa...,https://ikman.lk/en/ad/keselwatta-road-for-sal...,Fonseka,Premium-Member,2021-11-14 17:25:00,"Gampola, Kandy, Sri Lanka",80.570274,7.163649,0
33,"Brand New 2 Storey, House fo Sale, Pelawatte, ...","Posted on 17 Nov 4:05 pm, Battaramulla, Colombo","Rs 39,500,000",Pelawathe,4,12.0 perches,4,"4,200.0 sqft","Battaramulla, Colombo",Architect Designed Brand New 2 Storied House A...,https://ikman.lk/en/ad/brand-new-2-storey-hous...,SN Property,Premium-Member,2021-11-17 16:05:00,"Battaramulla, Colombo, Sri Lanka",79.913892,6.897711,1
34,3 Story House for sale in GALLE | KARAPITIYA f...,"Posted on 17 Nov 4:01 pm, Karapitiya, Galle","Rs 32,500,000",Karapitiya - Galle,6,11.0 perches,8,"4,000.0 sqft","Karapitiya, Galle",3 Houses Apartment for sale in GALLE | KARAPIT...,https://ikman.lk/en/ad/3-story-house-for-sale-...,à¶à·à¶½à·à¶½à· à¶à¶©à¶à¶©à¶¸à·,Premium-Member,2021-11-17 16:01:00,"Karapitiya, Galle, Sri Lanka",80.225761,6.067079,0
35,House for Sale Dehiwala for sale,"Posted on 29 Oct 8:11 am, Dehiwala, Colombo","Rs 35,000,000",Dehiwala Kalubowila,5,10.0 perches,6,"2,000.0 sqft","Dehiwala, Colombo","House for Sale Dehiwala Kalubowila, 10p, Groun...",https://ikman.lk/en/ad/house-for-sale-dehiwala...,Shan Multi Properties,Member,2021-10-29 08:11:00,"Dehiwala, Colombo, Sri Lanka",79.880242,6.838232,0
36,(94) Two Storey House for Sale - Talawatugoda ...,"Posted on 17 Nov 3:59 pm, Talawatugoda, Colombo","Rs 65,000,000",Talawatugoda Junction,5,27.5 perches,6,"5,000.0 sqft","Talawatugoda, Colombo",Two storey houseLand size - 27.5 perchesHouse ...,https://ikman.lk/en/ad/94-two-storey-house-for...,AK Construction & REAL ESTATE,Premium-Member,2021-11-17 15:59:00,"Talawatugoda, Colombo, Sri Lanka",80.016670,6.866670,0
37,Large House for Sale in Dematagoda for sale,"Posted on 14 Nov 3:53 pm, Colombo 9, Colombo","Rs 36,440,000",SCHOOL LANE,2,9.11 perches,4,"1,650.0 sqft","Colombo 9, Colombo",*CAR PARK & BACKYARD*LESS THAN 10 MINUTES TO A...,https://ikman.lk/en/ad/large-house-for-sale-in...,Rihan,Premium-Member,2021-11-14 15:53:00,"Colombo 9, Colombo, Sri Lanka",80.016670,6.866670,0
38,(92) Two Storey House for Sale - Rathmalana fo...,"Posted on 17 Nov 3:55 pm, Ratmalana, Colombo","Rs 40,000,000","Borupana Road, Rathmalana",4,12.1 perches,6,"3,000.0 sqft","Ratmalana, Colombo",Luxury two storey house for sale* 20 feet carp...,https://ikman.lk/en/ad/92-two-storey-house-for...,AK Construction & REAL ESTATE,Premium-Member,2021-11-17 15:55:00,"Ratmalana, Colombo, Sri Lanka",79.874891,6.817731,0
39,Thalawathugoda - House for sale for sale,"Posted on 17 Nov 3:54 pm, Talawatugoda, Colombo","Rs 49,500,000",NaN,4,10.0 perches,4,"4,000.0 sqft","Talawatugoda, Colombo",BRAND NEW LUXURY 2 STOREY HOUSE FOR SALE IN TH...,https://ikman.lk/en/ad/thalawathugoda-house-fo...,Siyane Real Estate,Premium-Member,2021-11-17 15:54:00,"Talawatugoda, Colombo, Sri Lanka",80.016670,6.866670,0
40,Brand New House for Sale in Piliyandala for sale,"Posted on 17 Nov 3:53 pm, Piliyandala, Colombo","Rs 25,500,000",Colombo bus road 1.8 Km Polgasovita,3,6.8 perches,4,"2,500.0 sqft","Piliyandala, Colombo",polgasovita juntion 1.4 kmKahathuduwa highway ...,https://ikman.lk/en/ad/brand-new-house-for-sal...,Asitha Properties,Premium-Member,2021-11-17 15:53:00,"Piliyandala, Colombo, Sri Lanka",79.922703,6.801844,1
41,3 Storied Residential House for Sale in Aruppo...,"Posted on 17 Nov 3:52 pm, Kandy City, Kandy","Rs 29,500,000",Kandy-Dharmashoka mawatha.,4,10.0 perches,7,"5,000.0 sqft","Kandy City, Kandy",10 Perch Land with 5000Sq Ft house.â¢ 07 La...,https://ikman.lk/en/ad/3-storied-residential-h...,First Team Real Estate,Premium-Member,2021-11-17 15:52:00,"Kandy City, Kandy, Sri Lanka",80.625828,7.295044,0
42,(24) Luxury Two Story House for Sale | Dehiwal...,"Posted on 17 Nov 3:52 pm, Dehiwala, Colombo","Rs 85,000,000","Sudarshana Road, Dehiwala",5,15.5 perches,5,"3,200.0 sqft","Dehiwala, Colombo",Luxury two storey house for sale 5 bedrooms 5 ...,https://ikman.lk/en/ad/24-luxury-two-story-hou...,AK Construction & REAL ESTATE,Premium-Member,2021-11-17 15:52:00,"Dehiwala, Colombo, Sri Lanka",79.880242,6.838232,0
43,House for Sale in Athurugiriya for sale,"Posted on 17 Nov 3:45 pm, Athurugiriya, Colombo","Rs 28,000,000","M D H Jayawardane Mw, Athurugiriya",4,10.0 perches,4,"2,800.0 sqft","Athurugiriya, Colombo",Luxury Brand New House For Sale In Athurugiri...,https://ikman.lk/en/ad/house-for-sale-in-athur...,Siyaka Land Sale.,Premium-Member,2021-11-17 15:45:00,"Athurugiriya, Colombo, Sri Lanka",79.989929,6.877246,0
44,(72) House for Sale - Nugegoda for sale,"Posted on 17 Nov 3:43 pm, Nugegoda, Colombo","Rs 47,000,000","Rubber Watta Road, Nugegoda",3,14.0 perches,3,"2,800.0 sqft","Nugegoda, Colombo",Luxury two story house for sale 3 bedrooms 3 a...,https://ikman.lk/en/ad/72-house-for-sale-nugeg...,AK Construction & REAL ESTATE,Premium-Member,2021-11-17 15:43:00,"Nugegoda, Colombo, Sri Lanka",79.893438,6.877014,0
45,Three Story House for Sale in Kalutara Panapit...,"Posted on 17 Nov 3:43 pm, Kalutara City, Kalutara","Rs 8,400,000",NaN,1,15.0 perches,3,"3,000.0 sqft","Kalutara City, Kalutara",à¶­à·à¶¸à·à¶½à· à¶±à·à·à·à¶à· à¶à· à·...,https://ikman.lk/en/ad/three-story-house-for-s...,à·à·à¶±à·à¶§à·âà¶»à· à·à·à¶¸à· à¶½à·...,Member,2021-11-17 15:43:00,"Kalutara City, Kalutara, Sri Lanka",80.166670,6.583330,0
46,Luxury Architecture design House for sale,"Posted on 17 Nov 3:38 pm, Boralesgamuwa, Colombo","Rs 75,000,000",Mtlavinia Attidiya,2,10.4 perches,3,"5,400.0 sqft","Boralesgamuwa, Colombo",Bellanwila walking pathKDU hospital Boralasgam...,https://ikman.lk/en/ad/luxury-architecture-des...,House Solution & Construction Rajkumar,Premium-Member,2021-11-17 15:38:00,"Boralesgamuwa, Colombo, Sri Lanka",79.901703,6.841060,0
47,A House Situated Within the Commercial Belt of...,"Posted on 17 Nov 3:32 pm, Kandy City, Kandy","Rs 18,500,000",Kandy-City,1,1.5 perches,2,600.0 sqft,"Kandy City, Kandy",â¢ Two storied1.5 perch house with commercia...,https://ikman.lk/en/ad/a-house-situated-within...,First Team Real Estate,Premium-Member,2021-11-17 15:32:00,"Kandy City, Kandy, Sri Lanka",80.625828,7.295044,0
48,à¶´à¶»à· 13 à·à¶¸à¶ à¶à¶­à· à·à¶§à·à¶±à...,"Posted on 17 Nov 3:31 pm, Kottawa, Colombo","Rs 29,500,000","Malabe Rd , Kottawa",4,13.0 perches,6,"3,800.0 sqft","Kottawa, Colombo",Two Storied House For Sale In Malabe Kottawa R...,https://ikman.lk/en/ad/pr-13-smg-itaa-vttinaa-...,Siyaka Land Sale.,Premium-Member,2021-11-17 15:31:00,"Kottawa, Colombo, Sri Lanka",79.965234,6.841388,0
49,Moratuwa house near Campus ð for sale,"Posted on 17 Nov 3:36 pm, Moratuwa, Colombo","Rs 65,000,000",Moratuwa,7,26.0 perches,8,"6,000.0 sqft","Moratuwa, Colombo",Moratuwa house 26 perches 6000 sqftBest place ...,https://ikman.lk/en/ad/moratuwa-house-near-cam...,House Solution & Construction Rajkumar,Premium-Member,2021-11-17 15:36:00,"Moratuwa, Colombo, Sri Lanka",79.888881,6.790527,0

In [223]:
# Replace the specified values in the 'Title' column with 'House'
data1
data1['Title'] = data1['Title'].apply(lambda x: 'House' if 'House' not in x else x)
# Show the first few rows of the updated dataframe
data1.head()

,Title,Sub_title,Price,Address,Baths,Land size,Beds,House size,Location,Description,Post_URL,Seller_name,Seller_type,published_date,Geo_Address,Lat,Lon,Brand New
0,House with Land for Sale in Matara for sale,"Posted on 06 Nov 2:32 pm, Matara City, Matara","Rs 5,400,000","Gangodagama Roard,Hakmana,Matara.",1,50.0 perches,3,"1,600.0 sqft","Matara City, Matara","Land for sale with house Matara,Hakmana Gangod...",https://ikman.lk/en/ad/house-with-land-for-sal...,Ishara Dilshan,Member,2021-11-06 14:32:00,"Matara City, Matara, Sri Lanka",80.500000,6.166670,0
1,House,"Posted on 24 Oct 7:27 am, Athurugiriya, Colombo","Rs 16,800,000",Athurugiriya Galwarusapare,3,8.0 perches,3,"1,480.0 sqft","Athurugiriya, Colombo",*House For Sale In Athurugiriya *Galwarusapare...,https://ikman.lk/en/ad/alut-kaamr-3-k-grh-bhaa...,DILRUWAN REAL ESTATE,Premium-Member,2021-10-24 07:27:00,"Athurugiriya, Colombo, Sri Lanka",79.989929,6.877246,0
2,Kelaniya - House on 20P Land for sale for sale,"Posted on 17 Nov 5:19 pm, Kelaniya, Gampaha","Rs 20,000,000",Kelaniya- Ranaviru Maldeniya Road,2,20.0 perches,3,"2,800.0 sqft","Kelaniya, Gampaha","Kelaniya- Biyagama road, Ranaviru Maladeniya R...",https://ikman.lk/en/ad/kelaniya-house-on-20p-l...,Provident Paradise (Pvt) Ltd,Member,2021-11-17 17:19:00,"Kelaniya, Gampaha, Sri Lanka",79.914926,6.951178,0
3,House For Sale in Pamankada Lane Wellawatte Co...,"Posted on 17 Nov 5:07 pm, Colombo 6, Colombo","Rs 187,000,000",Pamankada Lane Wellawatte Colombo.06,5,22.0 perches,5,"4,000.0 sqft","Colombo 6, Colombo",22 Perches House For Sale in Pamankada Lane We...,https://ikman.lk/en/ad/house-for-sale-in-paman...,Colombo Construction Property Developers,Premium-Member,2021-11-17 17:07:00,"Colombo 6, Colombo, Sri Lanka",80.016670,6.866670,0
4,House For Sale - Attidiya for sale,"Posted on 17 Nov 5:06 pm, Dehiwala, Colombo","Rs 1,300,000",MainRoad Attidiya,1,6.3 perches,2,900.0 sqft,"Dehiwala, Colombo",*à¶ à¶­à·à¶­à·à¶©à·à¶º à¶´à·âà¶»à¶¯à·à·...,https://ikman.lk/en/ad/house-for-sale-attidiya...,Lakdinu Houses,Member,2021-11-17 17:06:00,"Dehiwala, Colombo, Sri Lanka",79.880242,6.838232,0

In [224]:
# Modify the 'Title' column to keep only specific values
# specific_values = ['House', 'Luxury House', 'Apartment', 'Brand New', 'Villa', 'Hotel','Land']
specific_values = ['House', 'Luxury House', 'Apartment', 'Villa', 'Hotel']
data1['Title'] = data1['Title'].apply(lambda x: ' '.join([word for word in x.split() if word in specific_values]))
data1.groupby('Title')['Title'].agg('count')
data1['Title'].head()

0    House
1    House
2    House
3    House
4    House
Name: Title, dtype: object

In [225]:
data1.head()

,Title,Sub_title,Price,Address,Baths,Land size,Beds,House size,Location,Description,Post_URL,Seller_name,Seller_type,published_date,Geo_Address,Lat,Lon,Brand New
0,House,"Posted on 06 Nov 2:32 pm, Matara City, Matara","Rs 5,400,000","Gangodagama Roard,Hakmana,Matara.",1,50.0 perches,3,"1,600.0 sqft","Matara City, Matara","Land for sale with house Matara,Hakmana Gangod...",https://ikman.lk/en/ad/house-with-land-for-sal...,Ishara Dilshan,Member,2021-11-06 14:32:00,"Matara City, Matara, Sri Lanka",80.500000,6.166670,0
1,House,"Posted on 24 Oct 7:27 am, Athurugiriya, Colombo","Rs 16,800,000",Athurugiriya Galwarusapare,3,8.0 perches,3,"1,480.0 sqft","Athurugiriya, Colombo",*House For Sale In Athurugiriya *Galwarusapare...,https://ikman.lk/en/ad/alut-kaamr-3-k-grh-bhaa...,DILRUWAN REAL ESTATE,Premium-Member,2021-10-24 07:27:00,"Athurugiriya, Colombo, Sri Lanka",79.989929,6.877246,0
2,House,"Posted on 17 Nov 5:19 pm, Kelaniya, Gampaha","Rs 20,000,000",Kelaniya- Ranaviru Maldeniya Road,2,20.0 perches,3,"2,800.0 sqft","Kelaniya, Gampaha","Kelaniya- Biyagama road, Ranaviru Maladeniya R...",https://ikman.lk/en/ad/kelaniya-house-on-20p-l...,Provident Paradise (Pvt) Ltd,Member,2021-11-17 17:19:00,"Kelaniya, Gampaha, Sri Lanka",79.914926,6.951178,0
3,House,"Posted on 17 Nov 5:07 pm, Colombo 6, Colombo","Rs 187,000,000",Pamankada Lane Wellawatte Colombo.06,5,22.0 perches,5,"4,000.0 sqft","Colombo 6, Colombo",22 Perches House For Sale in Pamankada Lane We...,https://ikman.lk/en/ad/house-for-sale-in-paman...,Colombo Construction Property Developers,Premium-Member,2021-11-17 17:07:00,"Colombo 6, Colombo, Sri Lanka",80.016670,6.866670,0
4,House,"Posted on 17 Nov 5:06 pm, Dehiwala, Colombo","Rs 1,300,000",MainRoad Attidiya,1,6.3 perches,2,900.0 sqft,"Dehiwala, Colombo",*à¶ à¶­à·à¶­à·à¶©à·à¶º à¶´à·âà¶»à¶¯à·à·...,https://ikman.lk/en/ad/house-for-sale-attidiya...,Lakdinu Houses,Member,2021-11-17 17:06:00,"Dehiwala, Colombo, Sri Lanka",79.880242,6.838232,0

In [226]:
data1['Title'].value_counts()

Title
House              15071
                     228
Villa House           18
Apartment House        8
House Villa            1
Hotel House            1
Name: count, dtype: int64

In [227]:
#Assumed only following columns are important
data2= data1.loc[:,['Title','Price','Baths','Land size', 'Beds','House size', 'Location', 'Brand New']]

In [228]:
data2.head()

,Title,Price,Baths,Land size,Beds,House size,Location,Brand New
0,House,"Rs 5,400,000",1,50.0 perches,3,"1,600.0 sqft","Matara City, Matara",0
1,House,"Rs 16,800,000",3,8.0 perches,3,"1,480.0 sqft","Athurugiriya, Colombo",0
2,House,"Rs 20,000,000",2,20.0 perches,3,"2,800.0 sqft","Kelaniya, Gampaha",0
3,House,"Rs 187,000,000",5,22.0 perches,5,"4,000.0 sqft","Colombo 6, Colombo",0
4,House,"Rs 1,300,000",1,6.3 perches,2,900.0 sqft,"Dehiwala, Colombo",0

In [229]:
data2.isnull().sum()

Title         0
Price         0
Baths         0
Land size     0
Beds          0
House size    0
Location      0
Brand New     0
dtype: int64

In [230]:
data2.head()

,Title,Price,Baths,Land size,Beds,House size,Location,Brand New
0,House,"Rs 5,400,000",1,50.0 perches,3,"1,600.0 sqft","Matara City, Matara",0
1,House,"Rs 16,800,000",3,8.0 perches,3,"1,480.0 sqft","Athurugiriya, Colombo",0
2,House,"Rs 20,000,000",2,20.0 perches,3,"2,800.0 sqft","Kelaniya, Gampaha",0
3,House,"Rs 187,000,000",5,22.0 perches,5,"4,000.0 sqft","Colombo 6, Colombo",0
4,House,"Rs 1,300,000",1,6.3 perches,2,900.0 sqft,"Dehiwala, Colombo",0

In [231]:
# data2['Location'].unique()
data2[['Town','District']]=data2.Location.str.split(",",expand=True)
data2= data2.drop('Location',axis=1)

In [232]:
data2['Price'] = data2['Price'].str.replace('Rs', '').str.replace(',', '').astype(int)
data2['House size'] = data2['House size'].str.replace('sqft', '').str.replace(',', '').astype(float)
data2.head()

,Title,Price,Baths,Land size,Beds,House size,Brand New,Town,District
0,House,5400000,1,50.0 perches,3,1600.0,0,Matara City,Matara
1,House,16800000,3,8.0 perches,3,1480.0,0,Athurugiriya,Colombo
2,House,20000000,2,20.0 perches,3,2800.0,0,Kelaniya,Gampaha
3,House,187000000,5,22.0 perches,5,4000.0,0,Colombo 6,Colombo
4,House,1300000,1,6.3 perches,2,900.0,0,Dehiwala,Colombo

In [233]:
def acres_to_perches(row):
    if(len(row['Land size'].split())!=2):
        quantity = 'NaN'
    else:
        quantity, uom = row['Land size'].split()
        quantity = quantity.replace(',', '')
        if uom == 'acres':
            quantity=quantity*43560
    return quantity

data2['Land size'] = data2.apply(acres_to_perches, axis=1)

In [234]:

data2.head()

,Title,Price,Baths,Land size,Beds,House size,Brand New,Town,District
0,House,5400000,1,50.0,3,1600.0,0,Matara City,Matara
1,House,16800000,3,8.0,3,1480.0,0,Athurugiriya,Colombo
2,House,20000000,2,20.0,3,2800.0,0,Kelaniya,Gampaha
3,House,187000000,5,22.0,5,4000.0,0,Colombo 6,Colombo
4,House,1300000,1,6.3,2,900.0,0,Dehiwala,Colombo

In [235]:
data2.Beds.unique()

array(['3', '5', '2', '4', '10+', '9', '8', '6', '7', '1', '10'],
      dtype=object)

In [236]:
data2.Baths.unique()

array(['1', '3', '2', '5', '4', '10+', '7', '6', '8', '10', '9'],
      dtype=object)

In [237]:
data2.shape

(15327, 9)

In [238]:
def is_int(x):
    try:
        int(x)
    except:
        return False
    return True

data2= data2[data2['Baths'].apply(is_int)]
data2= data2[data2['Beds'].apply(is_int)]
data2.shape

(15269, 9)

In [239]:
data2.head()

,Title,Price,Baths,Land size,Beds,House size,Brand New,Town,District
0,House,5400000,1,50.0,3,1600.0,0,Matara City,Matara
1,House,16800000,3,8.0,3,1480.0,0,Athurugiriya,Colombo
2,House,20000000,2,20.0,3,2800.0,0,Kelaniya,Gampaha
3,House,187000000,5,22.0,5,4000.0,0,Colombo 6,Colombo
4,House,1300000,1,6.3,2,900.0,0,Dehiwala,Colombo

In [240]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15269 entries, 0 to 15326
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       15269 non-null  object
 1   Price       15269 non-null  int32
 2   Baths       15269 non-null  object
 3   Land size   15269 non-null  object
 4   Beds        15269 non-null  object
 5   House size  15269 non-null  float64
 6   Brand New   15269 non-null  int64
 7   Town        15269 non-null  object
 8   District    15269 non-null  object
dtypes: float64(1), int32(1), int64(1), object(6)
memory usage: 1.1+ MB

In [241]:
data2['Baths'] = data2['Baths'].astype('int32')
data2['Beds'] = data2['Beds'].astype('int32')
data2.dtypes

Title          object
Price           int32
Baths           int32
Land size      object
Beds            int32
House size    float64
Brand New       int64
Town           object
District       object
dtype: object

In [242]:
data2['Land size'] = pd.to_numeric(data2['Land size'], errors='coerce')

# Now convert to float
data2['Land size'] = data2['Land size'].astype(float)
data2.head()

,Title,Price,Baths,Land size,Beds,House size,Brand New,Town,District
0,House,5400000,1,50.0,3,1600.0,0,Matara City,Matara
1,House,16800000,3,8.0,3,1480.0,0,Athurugiriya,Colombo
2,House,20000000,2,20.0,3,2800.0,0,Kelaniya,Gampaha
3,House,187000000,5,22.0,5,4000.0,0,Colombo 6,Colombo
4,House,1300000,1,6.3,2,900.0,0,Dehiwala,Colombo

In [243]:
data2.dtypes

Title          object
Price           int32
Baths           int32
Land size     float64
Beds            int32
House size    float64
Brand New       int64
Town           object
District       object
dtype: object

In [244]:
# data2.corr()['Price']

In [245]:
data2['Title'].value_counts()

Title
House              15013
                     228
Villa House           18
Apartment House        8
House Villa            1
Hotel House            1
Name: count, dtype: int64

In [246]:
len(data2['Title'].value_counts())

6

In [247]:
data2['Brand New'].value_counts()

Brand New
0    13439
1     1830
Name: count, dtype: int64

In [249]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15269 entries, 0 to 15326
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       15269 non-null  object
 1   Price       15269 non-null  int32
 2   Baths       15269 non-null  int32
 3   Land size   15251 non-null  float64
 4   Beds        15269 non-null  int32
 5   House size  15269 non-null  float64
 6   Brand New   15269 non-null  int64
 7   Town        15269 non-null  object
 8   District    15269 non-null  object
dtypes: float64(2), int32(3), int64(1), object(3)
memory usage: 1014.0+ KB

In [250]:
data2.to_csv('cleaned_data.csv', sep='\t')

In [251]:
data2 = pd.get_dummies(data2)

In [252]:
data2.head(10)

,Price,Baths,Land size,Beds,House size,Brand New,Title_,Title_Apartment House,Title_Hotel House,Title_House,...,District_ Matale,District_ Matara,District_ Monaragala,District_ Mullativu,District_ Nuwara Eliya,District_ Polonnaruwa,District_ Puttalam,District_ Ratnapura,District_ Trincomalee,District_ Vavuniya
0,5400000,1,50.0,3,1600.0,0,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
1,16800000,3,8.0,3,1480.0,0,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,20000000,2,20.0,3,2800.0,0,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,187000000,5,22.0,5,4000.0,0,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,1300000,1,6.3,2,900.0,0,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
5,55000000,4,11.0,4,3300.0,0,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
6,45000000,4,10.0,4,4100.0,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
7,16700000,3,9.0,3,1400.0,0,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
8,50000000,4,10.0,4,4000.0,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
9,16000000,1,3000.0,3,2000.0,0,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
#Build a Model